### ISSUE TITLE
Custom Icon Error

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#115]
Hi, team.

I couldn't set my custom icon.
I think this code is wrong.

MFPPushIntentService
```
resourceId = context.getResources().getIdentifier(DRAWABLE+"/" + resourceName, DRAWABLE, context.getPackageName());
```

Fix to ...
```
resourceId = context.getResources().getIdentifier(resourceName, DRAWABLE, context.getPackageName());
```

(As a premise, we have to deploy the custom icon to drawable/push_notification_icon.png.)

What do you think?

**Comment by AnanthaKrish** [comment]
@Daiki-Kawanuma Hi, Thanks for pointing out the suggestion . I will make the change ASAP, and will let you know once the new SDK is out . 👍
