### ISSUE TITLE
Null pointer exception in AppID 

### ISSUE THREAD

**Issue by sabyasachiRepo** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#119]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.ibm.bluemix.appid.android.internal.authorizationmanager.AuthorizationManager com.ibm.bluemix.appid.android.internal.OAuthManager.getAuthorizationManager()' on a null object reference

**Comment by AnanthaKrish** [comment]
@sabyasachiRepo can please you raise the request in - https://github.com/ibm-cloud-security/appid-clientsdk-android.


Thanks .
