### ISSUE TITLE
Null MFPPushException.getErrorMessage() when registration fails

### ISSUE THREAD

**Issue by drcariel** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#30]
The response from the push service during registration failure returns a null response from the MFPPushException. This includes getErrorMessage(), getErrorCode(), getStatusLine(), getStatusCode() (which returns 0).

These null responses are evident in cases where the initialization is off (typo in route, appID, or client secret) and when push has not been configured on the Bluemix tile.

These 2 situations should have better failure responses, at least different Error Codes, instead of being null.

Are there any failure cases where these values will not be null?

**Comment by AnanthaKrish** [comment]
You can get the Status code through getStatusCode()  and Error message through  getErrorMessage(). Fix is available in 2.0.7
