### ISSUE TITLE
Cannot register using core sdk 2.2.+ init function

### ISSUE THREAD

**Issue by drcariel** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#31]
the newest release of Android core deprecated the old init function that included an application route. 

When I attempt to register after using this updated API, it fails with a null response, I assume the missing application route is to blame.

**Comment by drcariel** [comment]
When I use the old deprecated API with route, it works as expected.

This is the call that causes failure:

BMSClient.getInstance().initialize(this, "AppID", BMSClient.REGION_US_SOUTH);

**Comment by AnanthaKrish** [comment]
SDK will support Core SDK 2.2.+ .. The BMSClient init method  will take only AppRegion.
