### ISSUE TITLE
Change to MFPPushUrlBuilder.java in commit 351be558db4ac630dad5f89ba8c8033ff7d6a75e causes an exception

### ISSUE THREAD

**Issue by jdpescat** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#35]
String reWriteDomain = ""; was changed to String reWriteDomain = null;

When this line from MFPPushInvoker is run, and builder.getRewriteDomain() returns null (the new default value for reWriteDomain, an un checked java.lang.IllegalArgumentException exception is thrown by com.squareup.okhttp.Headers$Builder.add

request.addHeader(X_REWRITE_DOMAIN, builder.getRewriteDomain());

**Comment by AnanthaKrish** [comment]
Solved this issue.. Fix is there in 2.0.7
