### ISSUE TITLE
Push intent filter requires full package name

### ISSUE THREAD

**Issue by drcariel** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#38]
When adding an intent filter to open the app when the notification is tapped, it is expected the following syntax without the explicit package name:

```
<intent-filter>
                <action android:name=".IBMPushNotification" />

                <category android:name="android.intent.category.DEFAULT" />
 </intent-filter>
```

However, the above code does not open the expected activity. The user must explicitly enter the package name to make it work:

```
<intent-filter>
                <action android:name="com.ibm.hellopush.IBMPushNotification" />

                <category android:name="android.intent.category.DEFAULT" />
  </intent-filter>
```

This hurts our consumer experience, confirmed this issue with @dgonz7 and @mikerott

**Comment by sjimdickens** [comment]
We have to explicitly specify the package name because push sdk has a separate package name, and the client application will have a different package name.  Explicity specifying the package name and class name ensures that the appropriate intent is getting called.
