### ISSUE TITLE
getSenderIdFromServerAndRegisterInBackground response

### ISSUE THREAD

**Issue by SebastianSingle99** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#68]
I'm trying to register a device via 
`registerDeviceWithUserId(deviceId, new MFPPushResponseListener<String>() {...`
The class `MFPPushInvoker` receives the correct `senderId` in its`onSuccess` listener.
But afterwards the listener in `getSenderIdFromServerAndRegisterInBackground` receivces an empty response-object and the complete register-process has failed.
Any ideas?

**Comment by AnanthaKrish** [comment]
Did you configure FCM Cloud messaging credentials ?

**Comment by SebastianSingle99** [comment]
yes. The problem is in class `MFPPushInvoker`.

> @Override

> public void onSuccess(Response response) {
 >    logger.debug("MFPPushInvoker.onSuccess() - Success response in invoker is: "+ response.toString());
 >        responseListener.onSuccess(response);
    }


The response gets logged here and afterwards the response is null, because you can call methods like `getResponseText` or `getResponseJSON` just once as documented in the `Response` class.

**Comment by AnanthaKrish** [comment]
@SebastianSingle99 add the following in build.gradle(Module:app)

      compile 'com.ibm.mobilefirstplatform.clientsdk.android:core:2.2.7'

**Comment by SebastianSingle99** [comment]
This doesn't solve the problem. At the moment i have to include this lib as local module and comment out the log-statement and everything works.

**Comment by AnanthaKrish** [comment]
We will give the fix soon @SebastianSingle99
