### ISSUE TITLE
deregister fails after app relaunch

### ISSUE THREAD

**Issue by sairajkishore** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#73]
Hi,

When the app is registered for push notification and if we do deregister it work fine as expected ,but  when the app is registered for push and once we kill the app and launch the application and now if we do deregister then service call deregister is failing as the device id is becoming null in the URL.
could you please fix the issue.

**Comment by AnanthaKrish** [comment]
@sairajkishore Hi, thanks for pointing out the issue 👍 Will deliver a patch for this.

**Comment by AnanthaKrish** [comment]
@sairajkishore Please use 3.6.2 version of SDK. The issue is fixed
