### ISSUE TITLE
Conflict between PUSH and Watson Conversation

### ISSUE THREAD

**Issue by honeynatividad** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#76]
After updating my gradle 'com.ibm.watson.developer_cloud:conversation:3.8.1-SNAPSHOT', Im experiencing an error which is unable to register userID.
Is there a conflict between two gradles?

**Comment by AnanthaKrish** [comment]
@honeynatividad Hi, from where you are getting `com.ibm.watson.developer_cloud:conversation:3.8.1-SNAPSHOT` ?? I am able to get 3.8.0.. But Not 3.8.1-SNAPSHOT.. I am able to register with UserID in push service..

**Comment by honeynatividad** [comment]
Im using this sdk, which was instructed to use snapshot 
https://github.com/watson-developer-cloud/java-sdk

**Comment by AnanthaKrish** [comment]
@honeynatividad I am ble to register the app for push service after adding 3.8.1-Snapshot version.. There didn't face any conflicts.

**Comment by AnanthaKrish** [comment]
<img width="649" alt="screen shot 2017-07-14 at 3 56 31 pm" src="https://user-images.githubusercontent.com/16939018/28208789-1a3610dc-68ad-11e7-890d-303625e7caf1.png">
<img width="722" alt="screen shot 2017-07-14 at 3 56 38 pm" src="https://user-images.githubusercontent.com/16939018/28208788-1a30d5fe-68ad-11e7-9ee0-ec57bfef0414.png">
