### ISSUE TITLE
Missing permission

### ISSUE THREAD

**Issue by SebastianSingle99** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#78]
Hello,
seems that i'm missing a permission. This error only happens on Android 5 devices.
But the sample and the documentation don't mention anything about this permission. Only at runtime this permission gets validated during `MFPPush.initialize`.

`Caused by java.lang.RuntimeException: java.lang.RuntimeException: Your manifest is not allowed to work with push. Android Manifest Error: Missing permission in manifest: com.google.android.c2dm.permission.RECEIVE
       at com.ibm.mobilefirstplatform.clientsdk.android.push.api.MFPPush.initialize(MFPPush.java:285)...`

**Comment by AnanthaKrish** [comment]
@SebastianSingle99 Since we are using FCM we don't need `com.google.android.c2dm.permission.RECEIVE` ... which version of SDK you are using ?

**Comment by SebastianSingle99** [comment]
I'm using version 3.6.2. I just had a look at the library code. There is a call to  this method
made during `MFPush.initialize`:
`public static void checkManifest(Context context)  {
        verifyPermission(context, context.getPackageName() + ".permission.C2D_MESSAGE");
        verifyPermission(context, "com.google.android.c2dm.permission.RECEIVE");
    }`
That's the reason why my app crashes.

**Comment by AnanthaKrish** [comment]
@SebastianSingle99 I too got that... I have tested in API 21 and its working for me even with that code...  I will remove all the occurrences of GCM in the code and release a new version... That will fix these issues...

**Comment by AnanthaKrish** [comment]
@SebastianSingle99 You can try now.. new version of SDK is 3.6.3
