### ISSUE TITLE
OKHTTPCLIENT issue

### ISSUE THREAD

**Issue by honeynatividad** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#82]
Is there a conflict between OkHttpClient and push notification sdk using Android API Level 21 and 22?

**Comment by AnanthaKrish** [comment]
@honeynatividad No, there shouldn't be any OkHttpClient conflict.

**Comment by honeynatividad** [comment]
![errorimage](https://user-images.githubusercontent.com/4597060/30259451-fc22ddda-96f3-11e7-99b4-916cee69357b.jpg)

This is the error Im getting when i tried running my app.

**Comment by AnanthaKrish** [comment]
Looks like its a Bluemix Core SDK issue .. You can raise this issue in https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-android-core

**Comment by honeynatividad** [comment]
Thanks @AnanthaKrish ill post it on https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-android-core
