### ISSUE TITLE
Multiple sender support ?

### ISSUE THREAD

**Issue by nsteinmetz** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#83]
Hi

In our app, we need Push Notifications at 2 levels:
* At app level, we want to use push notificaiton to inform users or send some data notifications.
* We embed a partner SDK which relies on push notifications for some features.

Once we implemented Push notifications with Bluemix, we noticed some weird behaviours.

We assume that our partner SDK registers with its own SenderID and we know it uses the Amazon SNS system for push notification.

We have the feeling that the bmx sdk does not support multiple senders, as described in [FCM docs](https://firebase.google.com/docs/cloud-messaging/concept-options#receiving-messages-from-multiple-senders).

We guess the process is somehow:
* Partner SDK register itself with its own SenderID, token on AWS Platform
* BMX SDK find instanceid/serverid of the partner sdk and do nothing
* As a consequence, BMX SDK does not register itself for our part of the app.

Do you confirm our feeling ?

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
Answer from Bluemix support team:

> In our sample app we are able to use multiple senderID’s and retrieve appropriate tokens. In the google-services.json file you must specify all the firebase project’s numbers.
> It should be like this,

```json
{
  "project_info": {
    "project_number": "projectid1,projectid2,projectid3,..."
  }
}
```

**Comment by AnanthaKrish** [comment]
@nsteinmetz Hi, We only answered it.. couldn't update it here. Thanks for adding the reply here.
