### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by sairajkishore** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#86]
Could you let me know why we required these permissions for the sample app?  
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.USE_CREDENTIALS" />

**Comment by AnanthaKrish** [comment]
@sairajkishore Add only ,

```
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
```
