### ISSUE TITLE
Instructions to update gradle files are inverted

### ISSUE THREAD

**Issue by l2fprod** [ibm-bluemix-mobile-services/bms-clientsdk-android-push#89]
in https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-android-push/tree/Doc#include-client-push-sdk-with-gradle

it seems the first config to do in the module build.gradle and the second one in the project build.grade but the README says otherwise and this leads to an error as "compile" keyword is not supported in a Project file

![image](https://user-images.githubusercontent.com/12746550/32826675-a3ff20e0-c9e9-11e7-8cb4-b7118c18a7a0.png)

btw when creating my app in the Firebase console, Firebase makes you go through similar steps already. The only difference here is the IBM SDK. The google services are already added if you followed the Firebase stesp

**Comment by AnanthaKrish** [comment]
@l2fprod Thanks for pointing out the this. I will make the changes. 
Yeah Firebase have the same steps. But its always better to do a double check
